'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
a = 1
b = 0
fibo = 1
sfibo = 0
while fibo <= 4000000:
    fibo = a + b
    if fibo%2==0:
        sfibo += fibo
        print(sfibo)
    a = b
    b = fibo
    fibo += 1